export const messages: Array<string> = [
    'Reticulating Splines',
    'Loading Lions',
    'Eating Zebra Heart',
    'Hoarding Golden Beetles',
    'Battling Beetles',
    'Patrolling Sub-Males',
    'Barking Hybrids',
    'Waiting for Jaglions',
    'Gaining MORE Scars',
    'Randomly Applying Markings',
    'Demanding Mutations',
    'Chasing Poachers',
    'Balls',
    'Lab Testing Frogs',
    'Raising Impression',
]
